### ISSUE TITLE
"Error: comix not found on system."

### ISSUE THREAD

**Issue by danieltomasz** [corvidism/read-with-comix#1]
I use mcomix on ubuntu 18.04, I have mcomix installed but I get this error when I try to open comix from calibre, `subprocess.check_call(['mcomix'])` work for python2, so I suspect there is soemthing about the path the mcomic should open

the path itself is something like `~/Dokuments/Calibre Komiksy/comics autor/comix name folder/comix name.cbz` 

the only  related output when running calibre from console is 
`book ids: [61]`
 (where number is probably book id)

**Comment by corvidism** [comment]
Thanks for the report, I'll look into it.

**Comment by corvidism** [comment]
Have you tried to run mcomix directly? I don't have a Ubuntu 18.04 setup on hand, but I tried on Ubuntu 19.10 and mcomix doesn't run there at all, throws `Failed to load module "canberra-gtk-module"`. I didn't have time to debug that, but I think this AskUbuntu question might help: https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

**Comment by danieltomasz** [comment]
The error in the newest Calibre (after installing binary, not flatpak) is  gone!
 The mcomix was starting even without `"canberra-gtk-module"`. I am closing this issue. Thanks!
